project:
  type: website
  output-dir: docs  # GitHub Pages will serve from /docs folder

website:
  title: "aletras' blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Alessandro-Trasatti
      - icon: rss
        href: index.xml
  site-url: https://aletras.github.io/aletras-blog/
  description: "A blog documenting my technical studies and projects"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    code-annotations: hover
    css: 
      - styles.css
      - computer-modern-fonts.css
    toc: true
    toc-location: left
    code-tools: false

execute:
  freeze: auto  # Re-render only when source changes




  




